name: movies_app_surge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # A composable, Future-based library for making HTTP requests
  http: ^0.13.5  
  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Widgets that make it easy to integrate blocs and cubits into Flutter. Built to work with package:bloc
  flutter_bloc: ^8.1.2 
  # A dart package that helps implement the BLoC pattern.
  bloc: ^8.1.1
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.2.0
  # A widget provided to the flutter scroll component drop-down refresh and pull up load.
  pull_to_refresh: ^2.0.0
  # This plugin allows Flutter apps to discover network connectivity and configure themselves accordingly.
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^2.0.0
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.3.2
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.6.1
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300